In [4]:
import pandas as pd
# Carregando dados do arquivo CSV
url = 'https://raw.githubusercontent.com/KevennyJS/IA-RedesNeurais-Atividade6/main/diabetes.csv'
base_Treinamento = pd.read_csv(url,sep=',', encoding = 'latin1').values
print("---------------------------------")
print("Dados dos Pacientes - TREINAMENTO")
print("---------------------------------")
print(base_Treinamento)
print("---------------------------------")

# Extração dos Atributos a serem utilizadas pela rede
print("Atributos de Entrada")
print("---------------------------------")
print(base_Treinamento[:, 0:7])

print("----------------------------")
print("Classificação Supervisionada")
print("----------------------------")
print(base_Treinamento[:, 8])

---------------------------------
Dados dos Pacientes - TREINAMENTO
---------------------------------
[[  6.    148.     72.    ...   0.627  50.      1.   ]
 [  1.     85.     66.    ...   0.351  31.      0.   ]
 [  8.    183.     64.    ...   0.672  32.      1.   ]
 ...
 [  5.    121.     72.    ...   0.245  30.      0.   ]
 [  1.    126.     60.    ...   0.349  47.      1.   ]
 [  1.     93.     70.    ...   0.315  23.      0.   ]]
---------------------------------
Atributos de Entrada
---------------------------------
[[  6.    148.     72.    ...   0.     33.6     0.627]
 [  1.     85.     66.    ...   0.     26.6     0.351]
 [  8.    183.     64.    ...   0.     23.3     0.672]
 ...
 [  5.    121.     72.    ... 112.     26.2     0.245]
 [  1.    126.     60.    ...   0.     30.1     0.349]
 [  1.     93.     70.    ...   0.     30.4     0.315]]
----------------------------
Classificação Supervisionada
----------------------------
[1. 0. 1. 0. 1. 0. 1. 0. 1. 1. 0. 1. 0. 1. 1. 1. 1

In [5]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
from sklearn.linear_model import Perceptron

mms = preprocessing.MinMaxScaler()


def preProcessar(base, isteste=False):
    aux = np.array(base[:, 0])
    pregnancies = mms.fit_transform(aux.reshape(-1, 1))

    aux = np.array(base[:, 1])
    glucose = mms.fit_transform(aux.reshape(-1, 1))

    aux = np.array(base[:, 2])
    bloodPressure = mms.fit_transform(aux.reshape(-1, 1))

    aux = np.array(base[:, 3])
    skinThickness = mms.fit_transform(aux.reshape(-1, 1))

    aux = np.array(base[:, 4])
    insulin = mms.fit_transform(aux.reshape(-1, 1))

    aux = np.array(base[:, 5])
    BMI = mms.fit_transform(aux.reshape(-1, 1))

    aux = np.array(base[:, 6])
    DPF = mms.fit_transform(aux.reshape(-1, 1))

    aux = np.array(base[:, 7])
    age = mms.fit_transform(aux.reshape(-1, 1))

    if isteste == False:
        outcome = base[:, 8]

    atributos_norm = np.column_stack((pregnancies, glucose, bloodPressure, skinThickness, insulin, BMI, DPF, age))
    print("--------------------------------")
    print("Atributos de Entrada - Numéricos")
    print("--------------------------------")
    print(atributos_norm)

    if isteste == False:
        print("----------------------------------------")
        print("Classificação Supervisionada - Numéricos")
        print("----------------------------------------")
        diagnostico_norm = np.hstack((outcome))
        print(diagnostico_norm)
        return atributos_norm, diagnostico_norm
    return atributos_norm

# ================================================= Carregando dados do arquivo CSV

url = 'https://raw.githubusercontent.com/KevennyJS/IA-RedesNeurais-Atividade6/main/diabetes.csv'
base_Treinamento = pd.read_csv(url, sep=',', encoding='latin1').values
print("---------------------------------")
print("Dados dos Pacientes - TREINAMENTO")
print("---------------------------------")
print(base_Treinamento)
print("---------------------------------")

# Extração dos Atributos a serem utilizadas pela rede
print("Atributos de Entrada")
print("---------------------------------")
print(base_Treinamento[:, 0:8])

print("----------------------------")
print("Classificação Supervisionada")
print("----------------------------")
print(base_Treinamento[:, 8])

# ================================================= PRE PROCESSAMENTO

atributos_norm, diagnostico_norm = preProcessar(base_Treinamento, False)

# ================================================= Treinamento do Neurônio Perceptron

modelo = Perceptron()
modelo.fit(atributos_norm, diagnostico_norm)
print('Acurácia: %.3f' % modelo.score(atributos_norm, diagnostico_norm))

# ================================================= Validação do Aprendizado

url_testes = 'https://raw.githubusercontent.com/KevennyJS/IA-RedesNeurais-Atividade6/main/testes.csv'
base_Testes = pd.read_csv(url_testes, sep=',', encoding='latin1').values
print("----------------------------")
print("Dados dos Pacientes - TESTES")
print("----------------------------")
print(base_Testes)
print("---------------------------------")

# Extração dos Atributos a serem utilizadas pela rede
print("Atributos de Entrada")
print("---------------------------------")
print(base_Testes[:, 0:8])

# ==========================================================
atributos_norm = preProcessar(base_Testes, True)

base_Predicao = modelo.predict((atributos_norm))
print("Classificações: ", base_Predicao)


---------------------------------
Dados dos Pacientes - TREINAMENTO
---------------------------------
[[  6.    148.     72.    ...   0.627  50.      1.   ]
 [  1.     85.     66.    ...   0.351  31.      0.   ]
 [  8.    183.     64.    ...   0.672  32.      1.   ]
 ...
 [  5.    121.     72.    ...   0.245  30.      0.   ]
 [  1.    126.     60.    ...   0.349  47.      1.   ]
 [  1.     93.     70.    ...   0.315  23.      0.   ]]
---------------------------------
Atributos de Entrada
---------------------------------
[[  6.    148.     72.    ...  33.6     0.627  50.   ]
 [  1.     85.     66.    ...  26.6     0.351  31.   ]
 [  8.    183.     64.    ...  23.3     0.672  32.   ]
 ...
 [  5.    121.     72.    ...  26.2     0.245  30.   ]
 [  1.    126.     60.    ...  30.1     0.349  47.   ]
 [  1.     93.     70.    ...  30.4     0.315  23.   ]]
----------------------------
Classificação Supervisionada
----------------------------
[1. 0. 1. 0. 1. 0. 1. 0. 1. 1. 0. 1. 0. 1. 1. 1. 1